This notebook contains the code by which we created all the test cases for this research work

In [13]:
import numpy as np
import copy

### Test case generation Experiment 1

In [ ]:
#In general:
#V is n times m
#W is n times k
#H is k times m
#Description: We are generating matrix V for 1 x 1, 2 x 2, 3 x 3, 4 x 4 (with k = 1,2,3,4 respectively)
#Here V is generated by first generating W and H
seedctr = 0
for n in [1,2,3,4]:
    for i in range(100):
        np.random.seed(i)
        W = np.round(np.random.rand(n,n),2) #W has values in [0,1) rounded to two decimal places
        H = np.round(np.random.rand(n,n),2) #H has values in [0,1) rounded to two decimal places
        V = W @ H #Creating V from W and H
        store_dict = {}
        store_dict['V'] = copy.deepcopy(V)
        store_dict['W'] = copy.deepcopy(W)
        store_dict['H'] = copy.deepcopy(H)
        
        filename = "mat_"+str(n)+"x"+str(n)+"_"+str(i)+".npz"
        filepath = "./test_matrices/dirac3_exp1/size_" + str(n) + "x" + str(n) + "/" + filename 
        
        np.savez(filepath,**store_dict)
        print("seed:",seedctr)
        print(V)
        print("---")
        seedctr += 1



seed: 0
[[0.396]]
---
seed: 1
[[0.3024]]
---
seed: 2
[[0.0132]]
---
seed: 3
[[0.3905]]
---
seed: 4
[[0.5335]]
---
seed: 5
[[0.1914]]
---
seed: 6
[[0.2937]]
---
seed: 7
[[0.0624]]
---
seed: 8
[[0.8439]]
---
seed: 9
[[0.005]]
---
seed: 10
[[0.0154]]
---
seed: 11
[[0.0036]]
---
seed: 12
[[0.111]]
---
seed: 13
[[0.1872]]
---
seed: 14
[[0.3927]]
---
seed: 15
[[0.153]]
---
seed: 16
[[0.1144]]
---
seed: 17
[[0.1537]]
---
seed: 18
[[0.3315]]
---
seed: 19
[[0.076]]
---
seed: 20
[[0.531]]
---
seed: 21
[[0.0145]]
---
seed: 22
[[0.1008]]
---
seed: 23
[[0.494]]
---
seed: 24
[[0.672]]
---
seed: 25
[[0.5046]]
---
seed: 26
[[0.1612]]
---
seed: 27
[[0.3483]]
---
seed: 28
[[0.4088]]
---
seed: 29
[[0.2408]]
---
seed: 30
[[0.2432]]
---
seed: 31
[[0.2784]]
---
seed: 32
[[0.3182]]
---
seed: 33
[[0.1125]]
---
seed: 34
[[0.0312]]
---
seed: 35
[[0.1426]]
---
seed: 36
[[0.438]]
---
seed: 37
[[0.4324]]
---
seed: 38
[[0.3268]]
---
seed: 39
[[0.44]]
---
seed: 40
[[0.0246]]
---
seed: 41
[[0.0125]]
---
seed: 42
[[0.

### Test case generation for Experiment 2
Test set A

In [ ]:
#In general:
#V is n times m
#W is n times k
#H is k times m
#Description: We are generating matrix V for 4 x 5, 4 x 6, 4 x 7, 4 x 8 (NMF k=3, which in paper is called p)
#For the paper, we ended up using only 4 x 8
n = 4
k = 3

seedctr = 0
for m in [4,5,6,7,8]:
    print("Size:",n,'x',m)
    for i in range(100):
        np.random.seed(seedctr)
        V = np.round(np.random.rand(n,m),2)
        
        filename = "mat_"+str(n)+"x"+str(m)+"_"+str(i)+".npy"
        filepath = "./test_matrices/dirac3_exp2/size_" + str(n) + "x" + str(m) + "/" + filename 
        np.save(filepath,V)
        print("seed:",seedctr)
        print("V:",V)
        print("---")
        seedctr += 1



Size: 4 x 4
seed: 0
V: [[0.55 0.72 0.6  0.54]
 [0.42 0.65 0.44 0.89]
 [0.96 0.38 0.79 0.53]
 [0.57 0.93 0.07 0.09]]
---
seed: 1
V: [[0.42 0.72 0.   0.3 ]
 [0.15 0.09 0.19 0.35]
 [0.4  0.54 0.42 0.69]
 [0.2  0.88 0.03 0.67]]
---
seed: 2
V: [[0.44 0.03 0.55 0.44]
 [0.42 0.33 0.2  0.62]
 [0.3  0.27 0.62 0.53]
 [0.13 0.51 0.18 0.79]]
---
seed: 3
V: [[0.55 0.71 0.29 0.51]
 [0.89 0.9  0.13 0.21]
 [0.05 0.44 0.03 0.46]
 [0.65 0.28 0.68 0.59]]
---
seed: 4
V: [[0.97 0.55 0.97 0.71]
 [0.7  0.22 0.98 0.01]
 [0.25 0.43 0.78 0.2 ]
 [0.86 0.98 0.16 0.6 ]]
---
seed: 5
V: [[0.22 0.87 0.21 0.92]
 [0.49 0.61 0.77 0.52]
 [0.3  0.19 0.08 0.74]
 [0.44 0.16 0.88 0.27]]
---
seed: 6
V: [[0.89 0.33 0.82 0.04]
 [0.11 0.6  0.53 0.42]
 [0.34 0.62 0.44 0.74]
 [0.52 0.58 0.65 0.99]]
---
seed: 7
V: [[0.08 0.78 0.44 0.72]
 [0.98 0.54 0.5  0.07]
 [0.27 0.5  0.68 0.8 ]
 [0.38 0.07 0.29 0.91]]
---
seed: 8
V: [[0.87 0.97 0.87 0.53]
 [0.23 0.01 0.43 0.4 ]
 [0.52 0.48 0.56 0.54]
 [0.76 0.71 0.62 0.43]]
---
seed: 9
V: [[0.0

### Test case generation for Experiment 2
Test set B

In [ ]:
#In general:
#V is n times m
#W is n times k
#H is k times m
#Description: We are generating matrix V for 4 x 4, 4 x 5, 4 x 6, 4 x 7, 4 x 8 (with k = 3 )
#Here V is generated by first generating W and H
seedctr = 0
n = 4
k = 3
for m in [4,5,6,7,8]:
    for i in range(100):
        np.random.seed(seedctr)
        W = np.round(np.random.rand(n,k),2) #W has values in [0,1) rounded to two decimal places
        H = np.round(np.random.rand(k,m),2) #H has values in [0,1) rounded to two decimal places
        V = W @ H #Creating V from W and H
        store_dict = {}
        store_dict['V'] = copy.deepcopy(V)
        store_dict['W'] = copy.deepcopy(W)
        store_dict['H'] = copy.deepcopy(H)
        
        filename = "mat_"+str(n)+"x"+str(m)+"_"+str(i)+".npz"
        filepath = "./test_matrices/dirac3_exp2a/size_" + str(n) + "x" + str(m) + "/" + filename 
        
        np.savez(filepath,**store_dict)
        print("seed:",seedctr)
        print(V)
        print("---")
        seedctr += 1



seed: 0
[[0.9159 1.5891 0.8761 1.1439]
 [0.9532 1.3708 0.6644 0.921 ]
 [1.2094 1.9159 1.1666 1.5627]
 [0.7518 1.4331 0.8866 1.1349]]
---
seed: 1
[[0.3864 0.7728 0.1134 0.4254]
 [0.195  0.4353 0.0579 0.2931]
 [0.505  0.7512 0.1787 0.4733]
 [0.8364 1.3797 0.2889 0.9219]]
---
seed: 2
[[0.3632 0.2776 0.3412 0.405 ]
 [0.5825 0.4533 0.5781 0.4142]
 [0.706  0.4268 0.692  0.2376]
 [0.8324 0.4786 0.8035 0.3159]]
---
seed: 3
[[0.4529 0.7517 0.6862 0.6691]
 [0.6013 1.2622 0.9742 0.8187]
 [0.1027 0.1885 0.165  0.1729]
 [0.4154 0.4574 0.5094 0.3458]]
---
seed: 4
[[1.2665 2.0866 0.9435 1.9539]
 [0.7144 1.1778 0.3154 1.2894]
 [0.9529 1.2018 0.3547 0.8151]
 [0.4656 0.9156 0.258  1.1808]]
---
seed: 5
[[0.5795 0.3529 0.8005 0.6165]
 [0.9717 0.4589 1.2891 0.6851]
 [0.732  0.3602 1.0892 0.5845]
 [0.5604 0.2542 0.4248 0.2827]]
---
seed: 6
[[0.7744 1.2419 1.5249 1.7585]
 [0.141  0.5003 0.6028 0.5738]
 [0.637  0.7244 0.9861 1.1207]
 [0.7202 1.0728 1.3822 1.5222]]
---
seed: 7
[[0.4582 0.7746 0.8498 0.3304]
 [

### Test case generation for Experiment 3

In [ ]:
#Generate range of integer values
acceptable_vals = []
pow = 2
for i in range(2** (pow+1)):
    #acceptable_vals.append(round(1/(2**(pow+1) -1) * i,2)) #simplified the acceptable values list
    acceptable_vals.append(i)

In [3]:
acceptable_vals

[0, 1, 2, 3, 4, 5, 6, 7]

In [5]:
seedctr = 0
for n in [1,2,3,4]:
    for i in range(100):
        np.random.seed(i)
        W = np.random.choice(acceptable_vals,(n,n))  #W has int values in 0 to 7 range
        H = np.random.choice(acceptable_vals,(n,n)) #H has int values in 0 to 7 range
        V = W @ H #Creating V from W and H
        store_dict = {}
        store_dict['V'] = copy.deepcopy(V)
        store_dict['W'] = copy.deepcopy(W)
        store_dict['H'] = copy.deepcopy(H)
        
        filename = "mat_"+str(n)+"x"+str(n)+"_"+str(i)+".npz"
        filepath = "./test_matrices/dirac3_exp3/size_" + str(n) + "x" + str(n) + "/" + filename 
        
        np.savez(filepath,**store_dict)
        print("seed:",seedctr)
        print(V)
        print(W)
        print(H)
        print("---")
        seedctr += 1

seed: 0
[[28]]
[[4]]
[[7]]
---
seed: 1
[[15]]
[[5]]
[[3]]
---
seed: 2
[[0]]
[[0]]
[[7]]
---
seed: 3
[[0]]
[[2]]
[[0]]
---
seed: 4
[[12]]
[[2]]
[[6]]
---
seed: 5
[[18]]
[[3]]
[[6]]
---
seed: 6
[[2]]
[[2]]
[[1]]
---
seed: 7
[[28]]
[[7]]
[[4]]
---
seed: 8
[[12]]
[[3]]
[[4]]
---
seed: 9
[[24]]
[[6]]
[[4]]
---
seed: 10
[[5]]
[[1]]
[[5]]
---
seed: 11
[[7]]
[[1]]
[[7]]
---
seed: 12
[[9]]
[[3]]
[[3]]
---
seed: 13
[[0]]
[[2]]
[[0]]
---
seed: 14
[[0]]
[[3]]
[[0]]
---
seed: 15
[[0]]
[[0]]
[[5]]
---
seed: 16
[[6]]
[[1]]
[[6]]
---
seed: 17
[[7]]
[[7]]
[[1]]
---
seed: 18
[[6]]
[[2]]
[[3]]
---
seed: 19
[[30]]
[[5]]
[[6]]
---
seed: 20
[[6]]
[[3]]
[[2]]
---
seed: 21
[[7]]
[[1]]
[[7]]
---
seed: 22
[[20]]
[[5]]
[[4]]
---
seed: 23
[[18]]
[[3]]
[[6]]
---
seed: 24
[[6]]
[[2]]
[[3]]
---
seed: 25
[[24]]
[[4]]
[[6]]
---
seed: 26
[[30]]
[[5]]
[[6]]
---
seed: 27
[[0]]
[[3]]
[[0]]
---
seed: 28
[[1]]
[[1]]
[[1]]
---
seed: 29
[[15]]
[[5]]
[[3]]
---
seed: 30
[[25]]
[[5]]
[[5]]
---
seed: 31
[[14]]
[[2]]
[[7]]
---
see

### Test case generation for Experiment 4
Test set B

$4 \times 8$ matrix V factored into $4 \times 3$ W and $3 \times 8$ H
Here we prepare W and H beforehand

In [2]:
acceptable_vals = []
pow = 2
for i in range(2** (pow+1)):
    #acceptable_vals.append(round(1/(2**(pow+1) -1) * i,2)) #simplified the acceptable values list
    acceptable_vals.append(i)

In [4]:
acceptable_vals

[0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
#In general:
#V is n times m
#W is n times k
#H is k times m
#Description: We are generating matrix V for 4 x 8 (with k = 3 respectively)
#Here V is generated by first generating W and H
seedctr = 0
n = 4
k = 3
for m in [8]:
    for i in range(100):
        np.random.seed(seedctr)
        W = np.random.choice(acceptable_vals,(n,k))  #W has int values in 0 to 7 range
        H = np.random.choice(acceptable_vals,(k,m)) #H has int values in 0 to 7 range
        V = W @ H #Creating V from W and H
        store_dict = {}
        store_dict['V'] = copy.deepcopy(V)
        store_dict['W'] = copy.deepcopy(W)
        store_dict['H'] = copy.deepcopy(H)
        
        filename = "mat_"+str(n)+"x"+str(m)+"_"+str(i)+".npz"
        filepath = "./test_matrices/dirac3_exp4a/size_" + str(n) + "x" + str(m) + "/" + filename 
        
        np.savez(filepath,**store_dict)
        print("seed:",seedctr)
        print(V)
        print("---")
        seedctr += 1

seed: 0
[[83 77 78 62 15 23 58 36]
 [33 21 24 30  9  3 24 18]
 [59 70 68 46  3 19 44 15]
 [52 56 55 38  6 17 37 18]]
---
seed: 1
[[58 74 39 48 67 45 20 36]
 [47 41 16 32 28 35 15 29]
 [77 88 39 60 82 72 23 39]
 [ 5  6  2  4  7  7  1  1]]
---
seed: 2
[[43 43 70 79 31 47 38 34]
 [33 33 51 60 24 39 30 24]
 [26 18 25 35 23 32 16 14]
 [60 32 52 69 57 62 24 36]]
---
seed: 3
[[ 8  4  6 17 18 13  3 10]
 [ 3  3  6 15 21 18  0 12]
 [50 35 45 65 20 15 20 20]
 [29 19 26 48 33 25 11 22]]
---
seed: 4
[[75 69 83 57 68 61 60  8]
 [37 29 36 41 37  9  3 20]
 [63 45 52 51 61 17 12 28]
 [39 33 38 23 35 29 30  4]]
---
seed: 5
[[88 84 46 60 80 56 81 16]
 [87 78 54 54 89 62 89 17]
 [ 5  7  0  3  4  5  3  1]
 [89 85 48 57 86 63 85 17]]
---
seed: 6
[[16 26 17 12 39  9 29 25]
 [30 47 29 22 71 17 52 48]
 [29 37  7 18 57 15 34 56]
 [24 36 11 16 53 11 33 45]]
---
seed: 7
[[ 18  13  73  46  34   7  66  70]
 [ 18  24  66  45  36  21  66  57]
 [ 36  31 103  79  58  28  90  91]
 [ 38  43  69  72  54  49  60  48]]
---


### Test case generation for Experiment 4
Test set B

In [2]:
n = 4
m = 8
k = 3
max_val = 7
acceptable_vals = [i for i in range(max_val*max_val*k)] #acceptable values go from 0 to the maximum it can be with matrix multiplication for one cell

In [16]:
#In general:
#V is n times m
#W is n times k
#H is k times m
#Description: We are generating matrix V for 4 x 8 (with k = 3 respectively)
#Here V is generated without making W and H
seedctr = 0
n = 4
k = 3
for m in [8]:
    for i in range(100):
        np.random.seed(seedctr)
        V = np.random.choice(acceptable_vals,(n,m))  #V has int values in 0 to max_val^2 * k
        filename = "mat_"+str(n)+"x"+str(m)+"_"+str(i)+".npy"
        filepath = "./test_matrices/dirac3_exp4/size_" + str(n) + "x" + str(m) + "/" + filename 
        
        np.save(filepath,V)
        print("seed:",seedctr)
        print(V)
        print("---")
        seedctr += 1

seed: 0
[[ 47 117  67 103   9  21  36  87]
 [ 70  88 140  58  39  87  88  81]
 [ 25  77  72   9 115  79  82  99]
 [ 29 142  32   9 127  32  31 114]]
---
seed: 1
[[ 37 140  72 137 133  79 144 129]
 [ 71 134  25  20 101 146 139 142]
 [ 50  68  96  86 141 137   7  63]
 [ 61  22  57   1 128  60   8 141]]
---
seed: 2
[[ 15  72  22  43  75 104   7  95]
 [ 75  47  63  31 124 116  37 102]
 [  4 107  51 103  38  33  58 124]
 [ 67  69  88  46  95 121  31  80]]
---
seed: 3
[[106 131   0  21 107 138 119  93]
 [142  26  81  66   2  60 129  90]
 [ 69 104 110  97 106  62   7  33]
 [123  79  37  20  94  49 127  28]]
---
seed: 4
[[122 129 104  87  50 137  58 103]
 [109  94  55  57 104  44  38 126]
 [ 52 131   0  21  56 117  30 136]
 [ 49  66  87  32 126   3 114 115]]
---
seed: 5
[[ 99 118 144  73   8 112   7 143]
 [113  80  27  44  65  30  86 125]
 [146 121 137 106  41 129 103 144]
 [  5  58   0 132 110 105  27  31]]
---
seed: 6
[[138 106 109  79 106  80  62  25]
 [  1  75  77  26 110  68   8 130]
 [ 3